// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: grpcs/socket_cluster_gateway/proto/gateway/gateway.proto

package gateway

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IsOnlineRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
}

func (x *IsOnlineRequest) Reset() {
	*x = IsOnlineRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcs_socket_cluster_gateway_proto_gateway_gateway_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsOnlineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsOnlineRequest) ProtoMessage() {}

func (x *IsOnlineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcs_socket_cluster_gateway_proto_gateway_gateway_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsOnlineRequest.ProtoReflect.Descriptor instead.
func (*IsOnlineRequest) Descriptor() ([]byte, []int) {
	return file_grpcs_socket_cluster_gateway_proto_gateway_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *IsOnlineRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type IsOnlineResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code     int64  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg      string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	IsOnline bool   `protobuf:"varint,3,opt,name=is_online,json=isOnline,proto3" json:"is_online,omitempty"`
}

func (x *IsOnlineResponse) Reset() {
	*x = IsOnlineResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcs_socket_cluster_gateway_proto_gateway_gateway_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsOnlineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsOnlineResponse) ProtoMessage() {}

func (x *IsOnlineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcs_socket_cluster_gateway_proto_gateway_gateway_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsOnlineResponse.ProtoReflect.Descriptor instead.
func (*IsOnlineResponse) Descriptor() ([]byte, []int) {
	return file_grpcs_socket_cluster_gateway_proto_gateway_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *IsOnlineResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *IsOnlineResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *IsOnlineResponse) GetIsOnline() bool {
	if x != nil {
		return x.IsOnline
	}
	return false
}

type SendToClientIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Data     []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *SendToClientIdRequest) Reset() {
	*x = SendToClientIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcs_socket_cluster_gateway_proto_gateway_gateway_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendToClientIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendToClientIdRequest) ProtoMessage() {}

func (x *SendToClientIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcs_socket_cluster_gateway_proto_gateway_gateway_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendToClientIdRequest.ProtoReflect.Descriptor instead.
func (*SendToClientIdRequest) Descriptor() ([]byte, []int) {
	return file_grpcs_socket_cluster_gateway_proto_gateway_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *SendToClientIdRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *SendToClientIdRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type SendToClientIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int64  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *SendToClientIdResponse) Reset() {
	*x = SendToClientIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcs_socket_cluster_gateway_proto_gateway_gateway_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendToClientIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendToClientIdResponse) ProtoMessage() {}

func (x *SendToClientIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcs_socket_cluster_gateway_proto_gateway_gateway_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendToClientIdResponse.ProtoReflect.Descriptor instead.
func (*SendToClientIdResponse) Descriptor() ([]byte, []int) {
	return file_grpcs_socket_cluster_gateway_proto_gateway_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *SendToClientIdResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SendToClientIdResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type SendToClientIdsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientIds []string `protobuf:"bytes,1,rep,name=client_ids,json=clientIds,proto3" json:"client_ids,omitempty"`
	Data      []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *SendToClientIdsRequest) Reset() {
	*x = SendToClientIdsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcs_socket_cluster_gateway_proto_gateway_gateway_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendToClientIdsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendToClientIdsRequest) ProtoMessage() {}

func (x *SendToClientIdsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcs_socket_cluster_gateway_proto_gateway_gateway_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendToClientIdsRequest.ProtoReflect.Descriptor instead.
func (*SendToClientIdsRequest) Descriptor() ([]byte, []int) {
	return file_grpcs_socket_cluster_gateway_proto_gateway_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *SendToClientIdsRequest) GetClientIds() []string {
	if x != nil {
		return x.ClientIds
	}
	return nil
}

func (x *SendToClientIdsRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type SendToClientIdsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int64  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *SendToClientIdsResponse) Reset() {
	*x = SendToClientIdsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcs_socket_cluster_gateway_proto_gateway_gateway_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendToClientIdsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendToClientIdsResponse) ProtoMessage() {}

func (x *SendToClientIdsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcs_socket_cluster_gateway_proto_gateway_gateway_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendToClientIdsResponse.ProtoReflect.Descriptor instead.
func (*SendToClientIdsResponse) Descriptor() ([]byte, []int) {
	return file_grpcs_socket_cluster_gateway_proto_gateway_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *SendToClientIdsResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SendToClientIdsResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_grpcs_socket_cluster_gateway_proto_gateway_gateway_proto protoreflect.FileDescriptor

var file_grpcs_socket_cluster_gateway_proto_gateway_gateway_proto_rawDesc = []byte{
	0x0a, 0x38, 0x67, 0x72, 0x70, 0x63, 0x73, 0x2f, 0x73, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x63,
	0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f, 0x67, 0x61, 0x74,
	0x65, 0x77, 0x61, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x67, 0x61, 0x74, 0x65,
	0x77, 0x61, 0x79, 0x22, 0x2e, 0x0a, 0x0f, 0x49, 0x73, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x49, 0x64, 0x22, 0x55, 0x0a, 0x10, 0x49, 0x73, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d,
	0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x1b, 0x0a,
	0x09, 0x69, 0x73, 0x5f, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x08, 0x69, 0x73, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x22, 0x48, 0x0a, 0x15, 0x53, 0x65,
	0x6e, 0x64, 0x54, 0x6f, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x22, 0x3e, 0x0a, 0x16, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x6f, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6d, 0x73, 0x67, 0x22, 0x4b, 0x0a, 0x16, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x6f, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d,
	0x0a, 0x0a, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x73, 0x12, 0x12, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x22, 0x3f, 0x0a, 0x17, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x6f, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x49, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d,
	0x73, 0x67, 0x32, 0xfa, 0x01, 0x0a, 0x0e, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3f, 0x0a, 0x08, 0x49, 0x73, 0x4f, 0x6e, 0x6c, 0x69, 0x6e,
	0x65, 0x12, 0x18, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x49, 0x73, 0x4f, 0x6e,
	0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x67, 0x61,
	0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x49, 0x73, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x51, 0x0a, 0x0e, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x6f,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1e, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77,
	0x61, 0x79, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x6f, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77,
	0x61, 0x79, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x6f, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x54, 0x0a, 0x0f, 0x53, 0x65, 0x6e,
	0x64, 0x54, 0x6f, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x73, 0x12, 0x1f, 0x2e, 0x67,
	0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x6f, 0x43, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x49, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e,
	0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x6f, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x0b, 0x5a, 0x09, 0x2e, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpcs_socket_cluster_gateway_proto_gateway_gateway_proto_rawDescOnce sync.Once
	file_grpcs_socket_cluster_gateway_proto_gateway_gateway_proto_rawDescData = file_grpcs_socket_cluster_gateway_proto_gateway_gateway_proto_rawDesc
)

func file_grpcs_socket_cluster_gateway_proto_gateway_gateway_proto_rawDescGZIP() []byte {
	file_grpcs_socket_cluster_gateway_proto_gateway_gateway_proto_rawDescOnce.Do(func() {
		file_grpcs_socket_cluster_gateway_proto_gateway_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpcs_socket_cluster_gateway_proto_gateway_gateway_proto_rawDescData)
	})
	return file_grpcs_socket_cluster_gateway_proto_gateway_gateway_proto_rawDescData
}

var file_grpcs_socket_cluster_gateway_proto_gateway_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_grpcs_socket_cluster_gateway_proto_gateway_gateway_proto_goTypes = []interface{}{
	(*IsOnlineRequest)(nil),         // 0: gateway.IsOnlineRequest
	(*IsOnlineResponse)(nil),        // 1: gateway.IsOnlineResponse
	(*SendToClientIdRequest)(nil),   // 2: gateway.SendToClientIdRequest
	(*SendToClientIdResponse)(nil),  // 3: gateway.SendToClientIdResponse
	(*SendToClientIdsRequest)(nil),  // 4: gateway.SendToClientIdsRequest
	(*SendToClientIdsResponse)(nil), // 5: gateway.SendToClientIdsResponse
}
var file_grpcs_socket_cluster_gateway_proto_gateway_gateway_proto_depIdxs = []int32{
	0, // 0: gateway.GatewayService.IsOnline:input_type -> gateway.IsOnlineRequest
	2, // 1: gateway.GatewayService.SendToClientId:input_type -> gateway.SendToClientIdRequest
	4, // 2: gateway.GatewayService.SendToClientIds:input_type -> gateway.SendToClientIdsRequest
	1, // 3: gateway.GatewayService.IsOnline:output_type -> gateway.IsOnlineResponse
	3, // 4: gateway.GatewayService.SendToClientId:output_type -> gateway.SendToClientIdResponse
	5, // 5: gateway.GatewayService.SendToClientIds:output_type -> gateway.SendToClientIdsResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpcs_socket_cluster_gateway_proto_gateway_gateway_proto_init() }
func file_grpcs_socket_cluster_gateway_proto_gateway_gateway_proto_init() {
	if File_grpcs_socket_cluster_gateway_proto_gateway_gateway_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpcs_socket_cluster_gateway_proto_gateway_gateway_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsOnlineRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcs_socket_cluster_gateway_proto_gateway_gateway_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsOnlineResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcs_socket_cluster_gateway_proto_gateway_gateway_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendToClientIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcs_socket_cluster_gateway_proto_gateway_gateway_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendToClientIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcs_socket_cluster_gateway_proto_gateway_gateway_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendToClientIdsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcs_socket_cluster_gateway_proto_gateway_gateway_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendToClientIdsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpcs_socket_cluster_gateway_proto_gateway_gateway_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpcs_socket_cluster_gateway_proto_gateway_gateway_proto_goTypes,
		DependencyIndexes: file_grpcs_socket_cluster_gateway_proto_gateway_gateway_proto_depIdxs,
		MessageInfos:      file_grpcs_socket_cluster_gateway_proto_gateway_gateway_proto_msgTypes,
	}.Build()
	File_grpcs_socket_cluster_gateway_proto_gateway_gateway_proto = out.File
	file_grpcs_socket_cluster_gateway_proto_gateway_gateway_proto_rawDesc = nil
	file_grpcs_socket_cluster_gateway_proto_gateway_gateway_proto_goTypes = nil
	file_grpcs_socket_cluster_gateway_proto_gateway_gateway_proto_depIdxs = nil
}
