// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.14.0
// source: grpcs/socket_cluster_gateway/proto/gateway/gateway.proto

package gateway

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	GatewayService_IsOnline_FullMethodName        = "/gateway.GatewayService/IsOnline"
	GatewayService_SendToClientId_FullMethodName  = "/gateway.GatewayService/SendToClientId"
	GatewayService_SendToClientIds_FullMethodName = "/gateway.GatewayService/SendToClientIds"
)

// GatewayServiceClient is the client API for GatewayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GatewayServiceClient interface {
	IsOnline(ctx context.Context, in *IsOnlineRequest, opts ...grpc.CallOption) (*IsOnlineResponse, error)
	SendToClientId(ctx context.Context, in *SendToClientIdRequest, opts ...grpc.CallOption) (*SendToClientIdResponse, error)
	SendToClientIds(ctx context.Context, in *SendToClientIdsRequest, opts ...grpc.CallOption) (*SendToClientIdsResponse, error)
}

type gatewayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGatewayServiceClient(cc grpc.ClientConnInterface) GatewayServiceClient {
	return &gatewayServiceClient{cc}
}

func (c *gatewayServiceClient) IsOnline(ctx context.Context, in *IsOnlineRequest, opts ...grpc.CallOption) (*IsOnlineResponse, error) {
	out := new(IsOnlineResponse)
	err := c.cc.Invoke(ctx, GatewayService_IsOnline_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) SendToClientId(ctx context.Context, in *SendToClientIdRequest, opts ...grpc.CallOption) (*SendToClientIdResponse, error) {
	out := new(SendToClientIdResponse)
	err := c.cc.Invoke(ctx, GatewayService_SendToClientId_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) SendToClientIds(ctx context.Context, in *SendToClientIdsRequest, opts ...grpc.CallOption) (*SendToClientIdsResponse, error) {
	out := new(SendToClientIdsResponse)
	err := c.cc.Invoke(ctx, GatewayService_SendToClientIds_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GatewayServiceServer is the server API for GatewayService service.
// All implementations must embed UnimplementedGatewayServiceServer
// for forward compatibility
type GatewayServiceServer interface {
	IsOnline(context.Context, *IsOnlineRequest) (*IsOnlineResponse, error)
	SendToClientId(context.Context, *SendToClientIdRequest) (*SendToClientIdResponse, error)
	SendToClientIds(context.Context, *SendToClientIdsRequest) (*SendToClientIdsResponse, error)
	mustEmbedUnimplementedGatewayServiceServer()
}

// UnimplementedGatewayServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGatewayServiceServer struct {
}

func (UnimplementedGatewayServiceServer) IsOnline(context.Context, *IsOnlineRequest) (*IsOnlineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsOnline not implemented")
}
func (UnimplementedGatewayServiceServer) SendToClientId(context.Context, *SendToClientIdRequest) (*SendToClientIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendToClientId not implemented")
}
func (UnimplementedGatewayServiceServer) SendToClientIds(context.Context, *SendToClientIdsRequest) (*SendToClientIdsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendToClientIds not implemented")
}
func (UnimplementedGatewayServiceServer) mustEmbedUnimplementedGatewayServiceServer() {}

// UnsafeGatewayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GatewayServiceServer will
// result in compilation errors.
type UnsafeGatewayServiceServer interface {
	mustEmbedUnimplementedGatewayServiceServer()
}

func RegisterGatewayServiceServer(s grpc.ServiceRegistrar, srv GatewayServiceServer) {
	s.RegisterService(&GatewayService_ServiceDesc, srv)
}

func _GatewayService_IsOnline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsOnlineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).IsOnline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_IsOnline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).IsOnline(ctx, req.(*IsOnlineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_SendToClientId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendToClientIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).SendToClientId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_SendToClientId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).SendToClientId(ctx, req.(*SendToClientIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_SendToClientIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendToClientIdsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).SendToClientIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_SendToClientIds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).SendToClientIds(ctx, req.(*SendToClientIdsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GatewayService_ServiceDesc is the grpc.ServiceDesc for GatewayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GatewayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gateway.GatewayService",
	HandlerType: (*GatewayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsOnline",
			Handler:    _GatewayService_IsOnline_Handler,
		},
		{
			MethodName: "SendToClientId",
			Handler:    _GatewayService_SendToClientId_Handler,
		},
		{
			MethodName: "SendToClientIds",
			Handler:    _GatewayService_SendToClientIds_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpcs/socket_cluster_gateway/proto/gateway/gateway.proto",
}
