// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg.proto

package node

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Msg struct {
	MsgType              int32    `protobuf:"varint,1,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Msg) Reset()         { *m = Msg{} }
func (m *Msg) String() string { return proto.CompactTextString(m) }
func (*Msg) ProtoMessage()    {}
func (*Msg) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{0}
}

func (m *Msg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Msg.Unmarshal(m, b)
}
func (m *Msg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Msg.Marshal(b, m, deterministic)
}
func (m *Msg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Msg.Merge(m, src)
}
func (m *Msg) XXX_Size() int {
	return xxx_messageInfo_Msg.Size(m)
}
func (m *Msg) XXX_DiscardUnknown() {
	xxx_messageInfo_Msg.DiscardUnknown(m)
}

var xxx_messageInfo_Msg proto.InternalMessageInfo

func (m *Msg) GetMsgType() int32 {
	if m != nil {
		return m.MsgType
	}
	return 0
}

func (m *Msg) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type ClientsMsg struct {
	ReceiveClientIds     []int64  `protobuf:"varint,1,rep,packed,name=receive_client_ids,json=receiveClientIds,proto3" json:"receive_client_ids,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientsMsg) Reset()         { *m = ClientsMsg{} }
func (m *ClientsMsg) String() string { return proto.CompactTextString(m) }
func (*ClientsMsg) ProtoMessage()    {}
func (*ClientsMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{1}
}

func (m *ClientsMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientsMsg.Unmarshal(m, b)
}
func (m *ClientsMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientsMsg.Marshal(b, m, deterministic)
}
func (m *ClientsMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientsMsg.Merge(m, src)
}
func (m *ClientsMsg) XXX_Size() int {
	return xxx_messageInfo_ClientsMsg.Size(m)
}
func (m *ClientsMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientsMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ClientsMsg proto.InternalMessageInfo

func (m *ClientsMsg) GetReceiveClientIds() []int64 {
	if m != nil {
		return m.ReceiveClientIds
	}
	return nil
}

func (m *ClientsMsg) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type AuthMsg struct {
	TransAddress         string   `protobuf:"bytes,1,opt,name=trans_address,json=transAddress,proto3" json:"trans_address,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthMsg) Reset()         { *m = AuthMsg{} }
func (m *AuthMsg) String() string { return proto.CompactTextString(m) }
func (*AuthMsg) ProtoMessage()    {}
func (*AuthMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{2}
}

func (m *AuthMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthMsg.Unmarshal(m, b)
}
func (m *AuthMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthMsg.Marshal(b, m, deterministic)
}
func (m *AuthMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthMsg.Merge(m, src)
}
func (m *AuthMsg) XXX_Size() int {
	return xxx_messageInfo_AuthMsg.Size(m)
}
func (m *AuthMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthMsg.DiscardUnknown(m)
}

var xxx_messageInfo_AuthMsg proto.InternalMessageInfo

func (m *AuthMsg) GetTransAddress() string {
	if m != nil {
		return m.TransAddress
	}
	return ""
}

func (m *AuthMsg) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func init() {
	proto.RegisterType((*Msg)(nil), "node.Msg")
	proto.RegisterType((*ClientsMsg)(nil), "node.ClientsMsg")
	proto.RegisterType((*AuthMsg)(nil), "node.AuthMsg")
}

func init() { proto.RegisterFile("msg.proto", fileDescriptor_c06e4cca6c2cc899) }

var fileDescriptor_c06e4cca6c2cc899 = []byte{
	// 198 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcc, 0x2d, 0x4e, 0xd7,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xc9, 0xcb, 0x4f, 0x49, 0x55, 0x32, 0xe1, 0x62, 0xf6,
	0x2d, 0x4e, 0x17, 0x92, 0xe4, 0xe2, 0xc8, 0x2d, 0x4e, 0x8f, 0x2f, 0xa9, 0x2c, 0x48, 0x95, 0x60,
	0x54, 0x60, 0xd4, 0x60, 0x0d, 0x62, 0xcf, 0x2d, 0x4e, 0x0f, 0xa9, 0x2c, 0x48, 0x15, 0x12, 0xe2,
	0x62, 0x49, 0x49, 0x2c, 0x49, 0x94, 0x60, 0x52, 0x60, 0xd4, 0xe0, 0x09, 0x02, 0xb3, 0x95, 0xfc,
	0xb8, 0xb8, 0x9c, 0x73, 0x32, 0x53, 0xf3, 0x4a, 0x8a, 0x41, 0x9a, 0x75, 0xb8, 0x84, 0x8a, 0x52,
	0x93, 0x53, 0x33, 0xcb, 0x52, 0xe3, 0x93, 0xc1, 0xa2, 0xf1, 0x99, 0x29, 0xc5, 0x12, 0x8c, 0x0a,
	0xcc, 0x1a, 0xcc, 0x41, 0x02, 0x50, 0x19, 0x88, 0x72, 0xcf, 0x94, 0x62, 0xac, 0xe6, 0x79, 0x71,
	0xb1, 0x3b, 0x96, 0x96, 0x64, 0x80, 0x0c, 0x53, 0xe6, 0xe2, 0x2d, 0x29, 0x4a, 0xcc, 0x2b, 0x8e,
	0x4f, 0x4c, 0x49, 0x29, 0x4a, 0x2d, 0x2e, 0x06, 0x3b, 0x87, 0x33, 0x88, 0x07, 0x2c, 0xe8, 0x08,
	0x11, 0x13, 0x92, 0xe2, 0xe2, 0x28, 0x48, 0x2c, 0x2e, 0x2e, 0xcf, 0x2f, 0x4a, 0x01, 0x9b, 0xc3,
	0x19, 0x04, 0xe7, 0x27, 0xb1, 0x81, 0xbd, 0x67, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x69, 0x35,
	0x54, 0x3b, 0xeb, 0x00, 0x00, 0x00,
}
