apiVersion: v1
kind: Service
metadata:
  labels:
    kt-component: dns-server
  name: kt-connect-dns
spec:
  ports:
  - name: dns
    port: 53
    protocol: UDP
    targetPort: 53
  - name: dns-tcp
    port: 53
    protocol: TCP
    targetPort: 53
  selector:
    kt-component: dns-server
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    kt-component: dns-server
  name: kt-connect-dns
spec:
  replicas: 1
  selector:
    matchLabels:
      kt-component: dns-server
  template:
    metadata:
      labels:
        kt-component: dns-server
    spec:
      containers:
      - image: registry.cn-hangzhou.aliyuncs.com/rdc-incubator/kt-connect-shadow:stable
        name: dns-server